# Write Kubernetes Deployment Script
apiVersion: apps/v1         #Specify Kubernetes version for deployment
kind: Deployment            #Define resource as Deployment
metadata:
  name: books-deployment    #Direct resource reference
  labels:
    app: books              #Labels
spec:
  replicas: 1               #Number of pods
  selector:                 #Identify managed pods
     matchLabels:
       app: books           #Match labels
  template:                 #Template for creating pods
    metadata:
      labels:
        app: books          #assign labels
    spec:                   #pods specification
      containers:           #List containers
        - name: books       #Name of containers
          image: llbooks:1                    #Container image 
          ports:
            - containerPort: 8000             #Port number the container listens on 
          env:
            - name: DATABASE_URL              #Sets the DATABASE_URL environment variable to the specified PostgreSQL connection string
              value: "postgresql://lyons_sit722_part2_user:ea19nWVMrtDgxCm2K0CgTntb3cAWinKO@dpg-cr3h3tbqf0us73e7do40-a.oregon-postgres.render.com/lyons_sit722_part2"
---
apiVersion: v1                 #Specifies the Kubernetes version for service
kind: Service                  #Define resource as Service
metadata:
  name: books-service          #Name of service
spec:
  selector:
    app: books                 #Labels
  type: NodePort               #Specify the service to be exposed on nodePort
  ports:                       #Define ports
    - protocol: TCP            #Specify the protocol
      port: 80                 #Internal port
      targetPort: 8000         #Service port
      nodePort: 30000          #External port
